# ============================================================
# Script 5
# Create Supplementary file 2
# ============================================================
#
# Purpose:
#
# This script reads in the individual Supplementary Table S2 files created
# during data wrangling and combines them into one Excel workbook called
# Supplementary_file_2.xlsx.
#
# The workbook contains:
#
# - Table S2.1: PubChem downloads
# - Table S2.2: Chemicalize batch output
# - Table S2.3: Chemical taxonomy
# - Table S2.4: Predominant charge
# - Table S2.5: eNTRYway batch output
# - Table S2.6: Ionisable nitrogen check
# - Table S2.7: All antibiotics
# - Table S2.8: All pollutants
#
# Files generated by previous scripts are read in from Files/Tables.
# Files manually created or checked are read in from Files/Read_in_files.
#
# The final workbook is saved in Files/Tables.
#
# ============================================================


## ---------- 0) Setup ----------

# Clear the global environment.
# Use with care because this removes all existing objects.
rm(list = ls())

# Load required packages.
library(dplyr)     # data wrangling: filter, mutate, rename, joins and pipes

library(openxlsx)     # read Excel files and create Excel workbooks with multiple sheets
library(here)         # make file paths portable across different computers
# by using paths relative to the project root

#Get package citations

# Get the citations for the R packages used in this script.
# These can be used in the methods section or supplementary information if needed.

citation("dplyr")
citation("openxlsx")
citation("here")


## ---------- 1) Read in Supplementary Table S2 files ----------

# Set working directory to where the created supplementary tables are saved.
setwd(here("Files", "Tables"))

# Check files in the created files directory.
list.files()

# Read in tables created by previous scripts.

Table_S2_1_Pubchem_Downloads <- read.xlsx(
  "Table_S2_1_Pubchem_Downloads.xlsx"
)

Table_S2_2_Chemicalize_batch <- read.xlsx(
  "Table_S2_2_Chemicalize_batch.xlsx"
)

Table_S2_3_Chemical_Taxonomy <- read.xlsx(
  "Table_S2_3_Chemical_Taxonomy.xlsx"
)

Table_S2_4_Predominant_charge_abs <- read.xlsx(
  "Table_S2_4_Predominant_charge.xlsx", sheet = 1
)

Table_S2_4_Predominant_charge_pols <- read.xlsx(
  "Table_S2_4_Predominant_charge.xlsx", sheet = 2
)



Table_S2_6_ionisable_N <- read.xlsx(
  "Table_S2_6_ionisable_N.xlsx"
)
  

Table_S2_5_eNTRy_way_Batch <- read.xlsx(
  "Table_S2_5_eNTRy_way_Batch.xlsx"
)

Table_S2_7_all_abs <- read.xlsx(
  "Table_S2_7_all_abs.xlsx"
)

Table_S2_8_all_pols <- read.xlsx(
  "Table_S2_8_all_pols.xlsx"
)


## ---------- 2) Join the Charge tables  ----------
colnames(Table_S2_4_Predominant_charge_abs)
colnames(Table_S2_4_Predominant_charge_pols)

Table_S2_4_Predominant_charge <- bind_rows(
  Table_S2_4_Predominant_charge_abs %>%
    mutate(TYPE = "Antibiotic"),
  Table_S2_4_Predominant_charge_pols %>%
    mutate(TYPE = "Pollutant")
) %>%
  select(
    TYPE,
    Compound_Name,
    Dominant_charge_pH_7_4,
    Dominant_charge_pH_7_4_code,
    per_dominant_charge_pH_7_4,
    Charge_pH_7_4_num
  )

# check it worked 

colnames(Table_S2_4_Predominant_charge)

nrow(Table_S2_4_Predominant_charge_abs)
# [1] 100
 
nrow(Table_S2_4_Predominant_charge_pols)
# [1] 119

 nrow(Table_S2_4_Predominant_charge)
# [1] 219
 
#It worked 
 
## ---------- 3) Check tables before combining ----------

# Check the first few rows of each table.

head(Table_S2_1_Pubchem_Downloads)
head(Table_S2_2_Chemicalize_batch)
head(Table_S2_3_Chemical_Taxonomy)
head(Table_S2_4_Predominant_charge)
head(Table_S2_5_eNTRy_way_Batch)
head(Table_S2_6_ionisable_N)
head(Table_S2_7_all_abs)
head(Table_S2_8_all_pols)

# Check column names of each table.

colnames(Table_S2_1_Pubchem_Downloads)
colnames(Table_S2_2_Chemicalize_batch)
colnames(Table_S2_3_Chemical_Taxonomy)
colnames(Table_S2_4_Predominant_charge)
colnames(Table_S2_5_eNTRy_way_Batch)
colnames(Table_S2_6_ionisable_N)
colnames(Table_S2_7_all_abs)
colnames(Table_S2_8_all_pols)


## ---------- 4) Create Supplementary file 2 workbook ----------

# Create a new Excel workbook.
Supplementary_file_2 <- createWorkbook()

# Add each supplementary table as a separate worksheet.

addWorksheet(Supplementary_file_2, "Table_S2_1_PubChem")
writeData(Supplementary_file_2, "Table_S2_1_PubChem", Table_S2_1_Pubchem_Downloads)

addWorksheet(Supplementary_file_2, "Table_S2_2_Chemicalize")
writeData(Supplementary_file_2, "Table_S2_2_Chemicalize", Table_S2_2_Chemicalize_batch)

addWorksheet(Supplementary_file_2, "Table_S2_3_Taxonomy")
writeData(Supplementary_file_2, "Table_S2_3_Taxonomy", Table_S2_3_Chemical_Taxonomy)

addWorksheet(Supplementary_file_2, "Table_S2_4_Charge")
writeData(Supplementary_file_2, "Table_S2_4_Charge", Table_S2_4_Predominant_charge)

addWorksheet(Supplementary_file_2, "Table_S2_5_eNTRYway")
writeData(Supplementary_file_2, "Table_S2_5_eNTRYway", Table_S2_5_eNTRy_way_Batch)

addWorksheet(Supplementary_file_2, "Table_S2_6_Ionisable_N")
writeData(Supplementary_file_2, "Table_S2_6_Ionisable_N", Table_S2_6_ionisable_N)

addWorksheet(Supplementary_file_2, "Table_S2_7_All_ABs")
writeData(Supplementary_file_2, "Table_S2_7_All_ABs", Table_S2_7_all_abs)

addWorksheet(Supplementary_file_2, "Table_S2_8_All_Pols")
writeData(Supplementary_file_2, "Table_S2_8_All_Pols", Table_S2_8_all_pols)


## ---------- 5) Save Supplementary file 2 ----------

# Set working directory to where the final supplementary workbook will be saved.
setwd(here("Files", "Tables"))

# Save the workbook.
saveWorkbook(
  Supplementary_file_2,
  "Supplementary_file_2.xlsx",
  overwrite = TRUE
)
